on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: Docker image tag

jobs:
  dbt-coverage:
    strategy:
      matrix:
        type: [ doc, test ]
    runs-on: [self-hosted, alpha]
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.GH_ACCESS_KEY_ID }}
          password: ${{ secrets.GH_SECRET_ACCESS_KEY }}
      - id: pull-local
        run: |
          docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPOSITORY }}:${{ inputs.tag }}
      - name: Check coverage
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPOSITORY }}:${{ inputs.tag }}
          options: |
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            -e DBT_PROFILES_DIR=${{ vars.DBT_PROJECT_DIR }}
            -e DBT_PROJECT_DIR=${{ vars.DBT_PROJECT_DIR }}
            -v ${{ github.workspace }}/${{ vars.DBT_PROJECT_DIR }}/target:/reports
          run: |
            set -e
            dbt docs generate
            cd ${{ vars.DBT_PROJECT_DIR }}            
            dbt-coverage compute ${{ matrix.type }} --cov-report /reports/coverage-${{ matrix.type }}.json --cov-fail-compare /reports/coverage-${{ matrix.type }}-before.json
            mv /reports/coverage-${{ matrix.type }}.json /reports/coverage-${{ matrix.type }}-before.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          file_pattern: 'hw_transforms/target/coverage-${{ matrix.type }}-before.json'
          commit_message: "DBT-Coverage: store ${{ matrix.type }} coverage report"
