name: Pre-commit hooks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:


  get-changed-files:
    name: Get List of Changed Files
    secrets: inherit
    uses: ./.github/workflows/_changed_files.yml

  sqlfmt:
    name: SQL Fmt
    secrets: inherit
    uses: ./.github/workflows/_sql_fmt.yml
    needs: [ get-changed-files ]
    with:
      changed-files: ${{ needs.get-changed-files.outputs.list-files }}

  sqlfluff:
    name: SQL Fluff
    secrets: inherit
    uses: ./.github/workflows/_sql_fluff.yml
    needs: [ get-changed-files ]
    with:
      changed-files: ${{ needs.get-changed-files.outputs.list-files }}

  dbtcheckpoint:
    name: DBT CheckPoint
    secrets: inherit
    uses: ./.github/workflows/_dbt_checkpoint.yml
    needs: [ get-changed-files ]
    with:
      changed-files: ${{ needs.get-changed-files.outputs.list-files }}
