name: Pull Request

on:
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gitleaks:
    name: Gitleaks
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false

  get-changed-files:
    name: Get List of Changed Files
    secrets: inherit
    uses: ./.github/workflows/_changed_files.yml
    needs: [ gitleaks ]

  sqlfmt:
    name: SQL Fmt
    secrets: inherit
    uses: ./.github/workflows/_sql_fmt.yml
    needs: [ get-changed-files ]
    with:
      changed-files: ${{ needs.get-changed-files.outputs.list-files }}

  sqlfluff:
    name: SQL Fluff
    secrets: inherit
    uses: ./.github/workflows/_sql_fluff.yml
    needs: [ get-changed-files ]
    with:
      changed-files: ${{ needs.get-changed-files.outputs.list-files }}

  build:
    name: Build
    secrets: inherit
    uses: ./.github/workflows/_build.yml
    needs: [ sqlfmt, sqlfluff ]
    with:
      build_stage: dev

