name: On Merge (Main)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build
    secrets: inherit
    uses: ./.github/workflows/_build.yml
    with:
      build_stage: prod

  run:
    name: DBT Run
    secrets: inherit
    uses: ./.github/workflows/_dbt_run.yml
    needs: [ build ]
    with:
      tag: ${{ needs.build.outputs.tag }}
      target: beta
      dbt_tag: hour
